import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'sjis_backend.settings')
django.setup()

from core.models import StaffMember

MEMBERS = [
    # Administration Body
    {
        "name": "Brother Leo Pereira, CSC",
        "role_type": "admin",
        "designation": "Administrator & Head of Institution",
        "department": "Executive Directorate & Holy Cross Council",
        "qualification": "M.Ed. (Boston College, USA), B.A. (Notre Dame University)",
        "image_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
        "email": "administrator@sjis-narinda.edu.bd",
        "bio": "Serving as Administrator, Brother Leo leads the institutional mission of holistic human formation, moral rectitude, and academic rigor in the Holy Cross tradition.",
        "order": 1,
        "is_featured": True,
        "is_active": True,
    },
    {
        "name": "Dr. Ronald Gomes",
        "role_type": "admin",
        "designation": "Vice Principal & Academic Dean",
        "department": "Academic Council & CAIE Standards",
        "qualification": "Ph.D. in Educational Administration, M.Sc. Applied Mathematics",
        "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop",
        "email": "vice.principal@sjis-narinda.edu.bd",
        "bio": "Overseeing curriculum compliance, pedagogical training, and Cambridge Assessment standards across O Level and A Level cohorts.",
        "order": 2,
        "is_featured": True,
        "is_active": True,
    },
    {
        "name": "Rev. Father Anthony Rozario, CSC",
        "role_type": "admin",
        "designation": "Chairman, School Governing Body",
        "department": "Congregation of Holy Cross Council",
        "qualification": "Licentiate in Theology (Rome), M.A. Philosophy (DU)",
        "image_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop",
        "email": "governing.board@sjis-narinda.edu.bd",
        "bio": "Guiding institutional policy, ethical development, philanthropic aid, and community outreach for St. Joseph International School.",
        "order": 3,
        "is_featured": True,
        "is_active": True,
    },
    {
        "name": "Ms. Marianne D'Souza",
        "role_type": "admin",
        "designation": "Director of Admissions & Student Welfare",
        "department": "Student Affairs Directorate",
        "qualification": "M.A. English (DU), Cambridge Certificate in Educational Leadership",
        "image_url": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop",
        "email": "admissions@sjis-narinda.edu.bd",
        "bio": "Directing applicant evaluation pathways, student pastoral care, and co-curricular guild mentoring across all academic divisions.",
        "order": 4,
        "is_featured": True,
        "is_active": True,
    },
    {
        "name": "Mr. Kazi Ashfaqur Rahman",
        "role_type": "admin",
        "designation": "Director of Finance & Campus Operations",
        "department": "Bursar & Corporate Affairs",
        "qualification": "FCA (ICAB), MBA in Finance (IBA, University of Dhaka)",
        "image_url": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=800&auto=format&fit=crop",
        "email": "bursar@sjis-narinda.edu.bd",
        "bio": "Overseeing long-term endowment investments, capital campus infrastructure expansion, and corporate governance compliance.",
        "order": 5,
        "is_featured": True,
        "is_active": True,
    },

    # Teachers (Academic Faculty)
    {
        "name": "Dr. Syed Aminul Islam",
        "role_type": "teacher",
        "designation": "Head of Science & Senior Cambridge Physics Faculty",
        "department": "Department of Physics",
        "qualification": "Ph.D. in Physics, M.Sc. (First Class, DU), Cambridge Examiner",
        "image_url": "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=800&auto=format&fit=crop",
        "email": "aminul.physics@sjis-narinda.edu.bd",
        "bio": "With over 22 years of pedagogical leadership, Dr. Islam mentors national science olympiad medalists and leads advanced Cambridge Physics.",
        "order": 10,
        "is_featured": True,
        "is_active": True,
    },
    {
        "name": "Ms. Nusrat Jahan",
        "role_type": "teacher",
        "designation": "Head of Mathematics Department",
        "department": "Department of Mathematics",
        "qualification": "M.Sc. in Applied Mathematics (DU), Cambridge Professional Fellow",
        "image_url": "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?q=80&w=800&auto=format&fit=crop",
        "email": "nusrat.math@sjis-narinda.edu.bd",
        "bio": "Specialist in Further Pure Mathematics, Calculus, and Statistics with multiple Josephite alumni securing Cambridge World Highest marks.",
        "order": 11,
        "is_featured": True,
        "is_active": True,
    },
    {
        "name": "Mr. Robert Anthony Cruze",
        "role_type": "teacher",
        "designation": "Senior Cambridge Chemistry Faculty & Lab Director",
        "department": "Department of Chemistry",
        "qualification": "M.Sc. in Chemistry (JU), Postgraduate Diploma in Education",
        "image_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800&auto=format&fit=crop",
        "email": "cruze.chem@sjis-narinda.edu.bd",
        "bio": "Leading analytical chemistry research, laboratory micro-experimentation, and practical chemistry workshops for senior scholars.",
        "order": 12,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Ms. Sharmin Akhter",
        "role_type": "teacher",
        "designation": "Head of English Language & World Literature",
        "department": "Department of English",
        "qualification": "M.A. in English Literature (DU), CELTA Certified",
        "image_url": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=800&auto=format&fit=crop",
        "email": "sharmin.english@sjis-narinda.edu.bd",
        "bio": "Directs rhetorical composition, classical literature, and coaches the championship St. Joseph Debating Society.",
        "order": 13,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Mr. Tanvir Hasan",
        "role_type": "teacher",
        "designation": "Lead Faculty in Computer Science, Robotics & AI",
        "department": "Department of Computer Science & Robotics",
        "qualification": "B.Sc. in Computer Science & Engineering (BUET)",
        "image_url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=800&auto=format&fit=crop",
        "email": "tanvir.cs@sjis-narinda.edu.bd",
        "bio": "Mentors algorithmic competitive programming, embedded Arduino/Raspberry Pi robotics, and international olympiad teams.",
        "order": 14,
        "is_featured": True,
        "is_active": True,
    },
    {
        "name": "Ms. Sabina Yasmin",
        "role_type": "teacher",
        "designation": "Senior Biology & Biotechnology Faculty",
        "department": "Department of Biological Sciences",
        "qualification": "M.Sc. in Biochemistry & Molecular Biology (DU)",
        "image_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=800&auto=format&fit=crop",
        "email": "sabina.bio@sjis-narinda.edu.bd",
        "bio": "Focuses on human cellular biology, genetics, and moderates the student Eco-Conservation & Nature Forum.",
        "order": 15,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Mr. John Benedict",
        "role_type": "teacher",
        "designation": "Senior Faculty in Economics & Business Studies",
        "department": "Department of Economics & Commerce",
        "qualification": "M.Sc. in Economics (LSE, UK), BBA (IBA)",
        "image_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop",
        "email": "benedict.econ@sjis-narinda.edu.bd",
        "bio": "Specializing in macroeconomics, market behavior, financial literacy, and moderator of the St. Joseph Business & Entrepreneurship Guild.",
        "order": 16,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Ms. Farhana Chowdhury",
        "role_type": "teacher",
        "designation": "Cambridge Primary & Middle Years Coordinator",
        "department": "Primary & Middle School Division",
        "qualification": "M.Ed. in Child Psychology & Early Education",
        "image_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=800&auto=format&fit=crop",
        "email": "farhana.primary@sjis-narinda.edu.bd",
        "bio": "Directs progressive early-years inquiry curriculum, foundational phonics, mathematical reasoning, and social development.",
        "order": 17,
        "is_featured": False,
        "is_active": True,
    },

    # Staff (Support & Operations)
    {
        "name": "Mr. David Rozario",
        "role_type": "staff",
        "designation": "Chief Registrar & Academic Records Officer",
        "department": "Office of the Registrar & Examinations",
        "qualification": "M.A., 18+ Years Institutional Registrar Experience",
        "image_url": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=800&auto=format&fit=crop",
        "email": "registrar@sjis-narinda.edu.bd",
        "bio": "Oversees official Cambridge examination candidacies, student registration registers, official academic transcripts, and credentials authentication.",
        "order": 20,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Engr. Faisal Ahmed",
        "role_type": "staff",
        "designation": "Chief Systems Administrator & Digital Infrastructure",
        "department": "Campus Information Technology Directorate",
        "qualification": "B.Sc. in EEE, Cisco CCNA, Red Hat Certified Engineer",
        "image_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
        "email": "it.admin@sjis-narinda.edu.bd",
        "bio": "Architect of the campus-wide gigabit optical network, examination computer labs, multi-layered cybersecurity, and smart learning boards.",
        "order": 21,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Ms. Rebecca Costa",
        "role_type": "staff",
        "designation": "Head Librarian & Digital Resource Center Manager",
        "department": "Central Academic Library",
        "qualification": "M.A. in Information Science & Library Management (DU)",
        "image_url": "https://images.unsplash.com/photo-1534751516642-a171edd2521d?q=80&w=800&auto=format&fit=crop",
        "email": "library@sjis-narinda.edu.bd",
        "bio": "Curates a repository of 35,000+ volumes, international academic research journals, audio-visual suites, and heritage archives.",
        "order": 22,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Mr. Subhash Chandra Roy",
        "role_type": "staff",
        "designation": "Senior Science Laboratories Superintendent",
        "department": "STEM Research & Practical Facilities",
        "qualification": "B.Sc. in Applied Chemistry, Lab Safety Certified",
        "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop",
        "email": "labs@sjis-narinda.edu.bd",
        "bio": "Maintains state-of-the-art laboratory safety standards, reagent logistics, and precision optical sensors for Cambridge practical assessments.",
        "order": 23,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Ms. Dilruba Parveen",
        "role_type": "staff",
        "designation": "Lead Student Counselor & Mental Wellness Officer",
        "department": "Student Counseling & Emotional Guidance Unit",
        "qualification": "M.S. in Clinical Psychology (DU), Certified Adolescent Counselor",
        "image_url": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800&auto=format&fit=crop",
        "email": "counseling@sjis-narinda.edu.bd",
        "bio": "Offers confidential guidance, adolescent emotional health support, academic stress mitigation, and career development roadmaps.",
        "order": 24,
        "is_featured": False,
        "is_active": True,
    },
    {
        "name": "Mr. Peter Gomez",
        "role_type": "staff",
        "designation": "Director of Campus Security & Estate Operations",
        "department": "Campus Security & Estate Logistics",
        "qualification": "Ex-Defense Services Logistics & Security Management",
        "image_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop",
        "email": "security@sjis-narinda.edu.bd",
        "bio": "Guarantees 24/7 student perimeter safety, high-definition automated gate surveillance, emergency readiness, and campus facilities upkeep.",
        "order": 25,
        "is_featured": False,
        "is_active": True,
    },
]

print("Seeding Faculty & Staff members...")
created_count = 0
for data in MEMBERS:
    obj, created = StaffMember.objects.update_or_create(
        name=data["name"],
        role_type=data["role_type"],
        defaults=data
    )
    if created:
        created_count += 1
    print(f"[{obj.get_role_type_display()}] {obj.name} - {obj.designation}")

print(f"\nDone! Seeded/Updated {len(MEMBERS)} staff members ({created_count} created). Total in DB: {StaffMember.objects.count()}")
