'use client';

import React, { useState } from 'react';
import { Database, UploadCloud, AlertTriangle, CheckCircle2, FileText, X } from 'lucide-react';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { restoreDataBackup } from '@/lib/api';

interface DatabaseRestoreModalProps {
  isOpen: boolean;
  onClose: () => void;
  token?: string;
  onRestoreSuccess: () => void;
}

export const DatabaseRestoreModal: React.FC<DatabaseRestoreModalProps> = ({
  isOpen,
  onClose,
  token,
  onRestoreSuccess,
}) => {
  const [fileData, setFileData] = useState<any>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successResult, setSuccessResult] = useState<any>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    setError(null);
    setSuccessResult(null);
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.name.endsWith('.json')) {
      setError('Please select a valid JSON backup file.');
      return;
    }

    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const json = JSON.parse(event.target?.result as string);
        if (!json.slides && !json.notices && !json.clubs && !json.gallery) {
          setError('File does not appear to be an authentic SJIS backup file.');
          return;
        }
        setFileData(json);
      } catch (err) {
        setError('Failed to parse JSON file. File may be corrupted.');
      }
    };
    reader.readAsText(file);
  };

  const handleExecuteRestore = async () => {
    if (!fileData) return;
    setLoading(true);
    setError(null);
    try {
      const res = await restoreDataBackup(fileData, token);
      setLoading(false);
      if (res.success) {
        setSuccessResult(res);
        onRestoreSuccess();
      } else {
        setError(res.message || 'Data restoration encountered an error.');
      }
    } catch (e: any) {
      setLoading(false);
      setError(e.message || 'Restoration failed.');
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={() => {
        setFileData(null);
        setFileName(null);
        setError(null);
        setSuccessResult(null);
        onClose();
      }}
      title="Disaster Recovery: Restore School Database"
      maxWidth="md"
    >
      <div className="space-y-5 text-xs text-slate-600">
        <div className="p-3.5 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900 flex items-start gap-2.5">
          <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <span className="font-bold text-amber-900 block">Notice on Data Restoration:</span>
            <p className="text-[11px] leading-relaxed">
              Restoring a snapshot will update or repopulate Hero Slides, Circular Notices, Co-Curricular Clubs, Gallery Media, and Admission Guidelines from the backup archive.
            </p>
          </div>
        </div>

        {/* Upload Box */}
        {!fileData && (
          <label className="border-2 border-dashed border-slate-300 hover:border-[#00183F] rounded-2xl p-8 flex flex-col items-center justify-center gap-3 cursor-pointer bg-slate-50 hover:bg-slate-100 transition-colors">
            <input type="file" accept=".json" onChange={handleFileUpload} className="hidden" />
            <div className="w-12 h-12 rounded-2xl bg-slate-200 flex items-center justify-center text-slate-600">
              <UploadCloud className="w-6 h-6 text-[#00183F]" />
            </div>
            <div className="text-center">
              <span className="font-bold text-slate-800 block text-xs">
                Select SJIS JSON Database Backup File
              </span>
              <span className="text-[10px] text-slate-400 block mt-0.5">
                Supports .json files generated by SJIS Control Center
              </span>
            </div>
          </label>
        )}

        {/* Preview Backup Contents */}
        {fileData && (
          <div className="border border-slate-200 rounded-2xl p-4 bg-slate-50 space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-200">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-[#00183F]" />
                <span className="font-bold text-slate-800">{fileName}</span>
              </div>
              <button
                onClick={() => {
                  setFileData(null);
                  setFileName(null);
                }}
                className="text-slate-400 hover:text-slate-600 p-1"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px]">
              <div className="p-2 rounded-lg bg-white border border-slate-200">
                <span className="text-slate-400 block">Slides</span>
                <span className="font-black text-[#00183F]">{fileData.slides?.length || 0} items</span>
              </div>
              <div className="p-2 rounded-lg bg-white border border-slate-200">
                <span className="text-slate-400 block">Notices</span>
                <span className="font-black text-[#00183F]">{fileData.notices?.length || 0} items</span>
              </div>
              <div className="p-2 rounded-lg bg-white border border-slate-200">
                <span className="text-slate-400 block">Clubs</span>
                <span className="font-black text-[#00183F]">{fileData.clubs?.length || 0} items</span>
              </div>
              <div className="p-2 rounded-lg bg-white border border-slate-200">
                <span className="text-slate-400 block">Gallery</span>
                <span className="font-black text-[#00183F]">{fileData.gallery?.length || 0} items</span>
              </div>
            </div>
          </div>
        )}

        {error && (
          <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs">
            {error}
          </div>
        )}

        {successResult && (
          <div className="p-3.5 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-800 flex items-center gap-2.5">
            <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
            <div>
              <span className="font-bold block">Database Restored Successfully!</span>
              <span className="text-[11px] text-emerald-700">
                All records synchronized with database.
              </span>
            </div>
          </div>
        )}

        <div className="pt-2 flex justify-end gap-3 border-t border-slate-100">
          <Button variant="ghost" size="sm" onClick={onClose}>
            {successResult ? 'Close' : 'Cancel'}
          </Button>

          {fileData && !successResult && (
            <Button
              variant="secondary"
              size="sm"
              disabled={loading}
              onClick={handleExecuteRestore}
              icon={<Database className="w-4 h-4" />}
            >
              {loading ? 'Restoring Database...' : 'Confirm & Restore Now'}
            </Button>
          )}
        </div>
      </div>
    </Modal>
  );
};
