# Generated by Django 6.1.1 on 2026-10-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='St. Joseph International School, Narinda', max_length=255)),
                ('tagline', models.CharField(default='Fostering Academic Excellence & Moral Integrity Since 1954', max_length=255)),
                ('history', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('principal_name', models.CharField(blank=True, default='Brother Leo Pereira, CSC', max_length=255)),
                ('principal_title', models.CharField(blank=True, default='Principal & Headmaster', max_length=255)),
                ('principal_message', models.TextField(blank=True)),
                ('principal_image_url', models.URLField(blank=True, max_length=1000)),
                ('stats', models.JSONField(blank=True, default=dict, help_text="e.g. {'students': '3,000+', 'teachers': '140+', 'clubs': '25+', 'success_rate': '100%'}")),
                ('core_values', models.JSONField(blank=True, default=list, help_text="List of objects: [{'title': 'Faith', 'desc': '...'}]")),
                ('facilities', models.JSONField(blank=True, default=list, help_text="List of facilities: [{'name': '...', 'desc': '...'}]")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Us Information',
            },
        ),
        migrations.CreateModel(
            name='AdmissionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026-2027', max_length=50)),
                ('title', models.CharField(default='Admissions Open for Academic Session 2026-2027', max_length=255)),
                ('overview', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('eligibility', models.JSONField(blank=True, default=list, help_text="[{'grade': 'Playgroup', 'age': '3-4 years', 'criteria': '...'}]")),
                ('application_steps', models.JSONField(blank=True, default=list, help_text="[{'step': 1, 'title': '...', 'description': '...'}]")),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('fee_structure', models.JSONField(blank=True, default=list, help_text="[{'grade': '...', 'admission_fee': '...', 'monthly_tuition': '...'}]")),
                ('important_dates', models.JSONField(blank=True, default=list, help_text="[{'event': '...', 'date': '...'}]")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('parent_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('grade_applying', models.CharField(max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Contacted / Interview Scheduled'), ('admitted', 'Admitted'), ('archived', 'Archived')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(choices=[('stem', 'STEM & Innovation'), ('arts', 'Cultural & Fine Arts'), ('debate', 'Debate & Public Speaking'), ('sports', 'Sports & Athletics'), ('service', 'Leadership & Social Welfare')], default='stem', max_length=50)),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Activity', help_text='Lucide icon name e.g. Cpu, Mic, Award, Compass', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('moderator_name', models.CharField(blank=True, max_length=200)),
                ('schedule', models.CharField(blank=True, default='Every Thursday, 2:30 PM - 4:00 PM', max_length=200)),
                ('key_activities', models.JSONField(blank=True, default=list, help_text='List of activity strings')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='List of achievement strings')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('campus', 'Campus & Heritage'), ('academics', 'Academic & STEM Labs'), ('sports', 'Sports & Athletics'), ('cultural', 'Cultural & Performing Arts'), ('events', 'Annual Events & Celebrations')], default='campus', max_length=50)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('image_url', models.URLField(max_length=1000)),
                ('video_url', models.URLField(blank=True, max_length=1000)),
                ('caption', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('admission', 'Admission'), ('events', 'Events & Celebrations'), ('exams', 'Examinations'), ('holidays', 'Holidays & Closures'), ('general', 'General Notice')], default='general', max_length=50)),
                ('content', models.TextField()),
                ('attachment_url', models.URLField(blank=True, max_length=1000)),
                ('publish_date', models.DateField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of notice board')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('badge', models.CharField(blank=True, default='Welcome to SJIS', max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('video_url', models.URLField(blank=True, max_length=1000)),
                ('cta_text', models.CharField(default='Apply For Admission', max_length=100)),
                ('cta_link', models.CharField(default='/admission', max_length=255)),
                ('secondary_cta_text', models.CharField(blank=True, default='Explore Campus', max_length=100)),
                ('secondary_cta_link', models.CharField(blank=True, default='/about', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
