# Generated by Django 6.1.1 on 2026-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='emergency_alert',
            field=models.JSONField(blank=True, default=dict, help_text="Emergency banner e.g. {'is_active': False, 'message': '', 'type': 'urgent', 'link_text': '', 'link_url': ''}"),
        ),
        migrations.AddField(
            model_name='admissioninquiry',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Internal staff notes'),
        ),
    ]
