# Generated by Django 6.1.1 on 2026-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutinfo_emergency_alert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, default='General', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='St. Joseph International School', max_length=255)),
                ('school_subtitle', models.CharField(blank=True, default='INTERNATIONAL SCHOOL • NARINDA', max_length=255)),
                ('phone_primary', models.CharField(default='+880 2-47118234', max_length=60)),
                ('phone_secondary', models.CharField(blank=True, default='+880 1711-234567', max_length=60)),
                ('email', models.EmailField(default='info@sjis-narinda.edu.bd', max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='Digits only with country code, e.g. 8801711234567', max_length=30)),
                ('address', models.TextField(default='83 Narinda Road, Narinda, Dhaka-1100, Bangladesh')),
                ('office_hours', models.CharField(default='Sun – Thu · 7:30 AM – 4:30 PM', max_length=255)),
                ('weekend_note', models.CharField(blank=True, default='Friday – Saturday: Academic Recess (Registrar by Appointment)', max_length=255)),
                ('accreditation_label', models.CharField(blank=True, default='Cambridge Registered Centre · BD084', max_length=255)),
                ('admissions_open', models.BooleanField(default=True)),
                ('admissions_label', models.CharField(default='Admissions 2026–27 Open', max_length=120)),
                ('map_embed_url', models.URLField(blank=True, default='', max_length=2000)),
                ('map_link', models.URLField(blank=True, default='https://maps.google.com/?q=St+Joseph+International+School+Narinda+Dhaka', max_length=1000)),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('youtube_url', models.URLField(blank=True, max_length=500)),
                ('security_note', models.CharField(blank=True, default='24/7 Security Controlled Entrance & Dedicated Visitor Registration Desk.', max_length=255)),
                ('highlights', models.JSONField(blank=True, default=list, help_text="[{'title','desc','icon'}] shown on the hero card")),
                ('inquiry_grades', models.JSONField(blank=True, default=list, help_text='Grade options in quick inquiry form')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g. Parent of Class IX Student', max_length=255)),
                ('badge', models.CharField(blank=True, default='Parent Voice', max_length=80)),
                ('avatar_url', models.URLField(blank=True, max_length=1000)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
