# Generated by Django 6.1.1 on 2026-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faq_sitesettings_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_notice_views',
            field=models.BooleanField(default=True, help_text='Show viewers count on circular notices'),
        ),
    ]
