# Generated by Django 6.1.1 on 2026-10-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_show_notice_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.TextField(blank=True, default='', help_text='Custom logo image URL or uploaded base64 data URL. If blank, official crest icon is used.'),
        ),
    ]
