# Generated by Django 6.1.1 on 2026-10-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_type', models.CharField(choices=[('admin', 'Administration Body & Leadership'), ('teacher', 'Academic Faculty & Teaching Staff'), ('staff', 'Support & Operations Staff')], default='teacher', max_length=40)),
                ('designation', models.CharField(help_text='e.g. Senior Cambridge Physics Faculty or Vice Principal', max_length=200)),
                ('department', models.CharField(help_text='e.g. Department of Science, Governing Council, IT & Systems', max_length=150)),
                ('image_url', models.TextField(blank=True, default='', help_text='Image URL or base64 data URL')),
                ('qualification', models.CharField(blank=True, help_text='e.g. M.Sc. in Physics (DU), Cambridge Certified', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature in leadership showcase')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faculty & Staff Member',
                'verbose_name_plural': 'Faculty & Staff Members',
                'ordering': ['order', 'id'],
            },
        ),
    ]
