# Generated by Django 6.1.1 on 2026-10-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staffmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='tagline',
            field=models.CharField(default='Fostering Academic Excellence & Moral Integrity', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accreditation_label',
            field=models.CharField(blank=True, default='Cambridge International Curriculum', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Administration Body & Leadership'), ('teacher', 'Academic Faculty & Teaching Staff'), ('office', 'Office & Administrative Staff'), ('staff', 'Support & Operations Staff')], default='teacher', max_length=40),
        ),
    ]
