# Generated by Django 6.1.1 on 2026-10-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aboutinfo_tagline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='department',
            field=models.CharField(blank=True, default='', help_text='e.g. Department of Science, Governing Council, IT & Systems', max_length=150),
        ),
    ]
