# Generated by Django 6.1.1 on 2026-10-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_staffmember_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='head_role_badge',
            field=models.CharField(blank=True, default='Head of Institution', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='heritage_label',
            field=models.CharField(blank=True, default='Years of Heritage', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='heritage_years',
            field=models.CharField(blank=True, default='70+', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='pillars',
            field=models.JSONField(blank=True, default=list, help_text="List of strings e.g. ['Cambridge Assessment International Education (CAIE)', ...]"),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='primary_button_text',
            field=models.CharField(blank=True, default='Read Full School History', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='primary_button_url',
            field=models.CharField(blank=True, default='/about', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='Admission Information', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='/admission', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='welcome_tag',
            field=models.CharField(blank=True, default='WELCOME TO ST. JOSEPH NARINDA', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='welcome_title',
            field=models.CharField(blank=True, default='Educating Hearts & Minds for Generations.', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='principal_title',
            field=models.CharField(blank=True, default='Administrator', max_length=255),
        ),
    ]
