# Generated by Django 6.1.1 on 2026-10-05 14:50

from django.db import migrations, models


OLD_NEW = {
    'phone_primary': ('+880 2-47118234', '+880 1746-866393'),
    'phone_secondary': ('+880 1711-234567', ''),
    'email': ('info@sjis-narinda.edu.bd', 'sjisnarinda2021@gmail.com'),
    'address': (
        '83 Narinda Road, Narinda, Dhaka-1100, Bangladesh',
        '32 Shah Shaheb Lane, Narinda, Dhaka-1100, Bangladesh',
    ),
}


def apply_real_contact(apps, schema_editor):
    """Replace only legacy placeholder values; never overwrite admin-edited data."""
    SiteSettings = apps.get_model('core', 'SiteSettings')
    for s in SiteSettings.objects.all():
        changed = []
        for field, (old, new) in OLD_NEW.items():
            if getattr(s, field) == old:
                setattr(s, field, new)
                changed.append(field)
        if changed:
            s.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_administrator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='principal_name',
            field=models.CharField(blank=True, default='Brother Roktim Chiran, CSC', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='32 Shah Shaheb Lane, Narinda, Dhaka-1100, Bangladesh'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='sjisnarinda2021@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(default='+880 1746-866393', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.RunPython(apply_real_contact, migrations.RunPython.noop),
    ]
