# Generated by Django 6.1.1 on 2026-10-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_update_contact_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='principal_image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='video_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sliderslide',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sliderslide',
            name='video_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
