# Generated by Django 6.1.1 on 2026-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_media_urls_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionguide',
            name='show_fees',
            field=models.BooleanField(default=True, help_text='If off, fee amounts are hidden from the public website and API (visible only to logged-in admins).'),
        ),
    ]
