# Generated by Django 6.1.1 on 2026-10-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_admissionguide_show_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image URLs for the club gallery'),
        ),
    ]
