# Generated by Django 6.1.1 on 2026-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ensure_administrator_roktim_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('category', models.CharField(choices=[('events', 'Events & Celebrations'), ('academic', 'Academic Achievements'), ('sports', 'Sports'), ('cultural', 'Arts & Culture'), ('campus', 'Campus Life'), ('general', 'General News')], default='events', max_length=50)),
                ('summary', models.CharField(blank=True, default='', help_text='Short teaser shown on cards (auto-generated from the story if empty)', max_length=400)),
                ('content', models.TextField(help_text='Full story. Blank lines create new paragraphs.')),
                ('image_url', models.TextField(blank=True, default='', help_text='Cover photo')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of additional photo URLs')),
                ('publish_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight as the lead story')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-is_featured', '-publish_date', '-created_at'],
            },
        ),
    ]
