# Generated by Django 6.1.1 on 2026-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Cambridge IGCSE Physics Syllabus 2026-2027', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('grade', models.CharField(help_text='e.g. Grade 9 - 10, Class 6, Playgroup', max_length=100)),
                ('subject', models.CharField(help_text='e.g. Physics, Pure Mathematics, English Language', max_length=150)),
                ('academic_year', models.CharField(default='2026-2027', max_length=50)),
                ('curriculum_section', models.CharField(choices=[('cambridge_primary', 'Cambridge Primary (Playgroup - Grade 5)'), ('cambridge_lower_sec', 'Cambridge Lower Secondary (Grade 6 - 8)'), ('cambridge_igcse', 'Cambridge Upper Secondary / IGCSE (Grade 9 - 10)'), ('gce_alevel', 'Cambridge Advanced / A-Level (Grade 11 - 12)'), ('general', 'General Curriculum & Assessment Overview')], default='cambridge_igcse', max_length=50)),
                ('file_url', models.TextField(help_text='PDF file URL or /circulars/...')),
                ('file_size', models.CharField(blank=True, default='PDF Document', help_text='e.g. 1.2 MB or 24 Pages', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Syllabus overview, objectives and assessment structure')),
                ('version', models.CharField(blank=True, default='v2026.1', max_length=50)),
                ('term', models.CharField(blank=True, default='Full Academic Year', help_text='e.g. Term 1, Term 2, or Full Academic Year', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Syllabus Item',
                'verbose_name_plural': 'Syllabus Items',
                'ordering': ['order', 'grade', 'subject', '-created_at'],
            },
        ),
    ]
