# Generated by Django 6.1.1 on 2026-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_syllabus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabusitem',
            options={'ordering': ['order', 'grade', '-created_at'], 'verbose_name': 'Syllabus Item', 'verbose_name_plural': 'Syllabus Items'},
        ),
        migrations.AddField(
            model_name='syllabusitem',
            name='subjects_included',
            field=models.TextField(blank=True, default='', help_text='e.g. English, Mathematics, Science, Bengali, ICT, Art & Craft'),
        ),
        migrations.AlterField(
            model_name='syllabusitem',
            name='curriculum_section',
            field=models.CharField(choices=[('cambridge_primary', 'Cambridge Primary (Playgroup - Grade 5)'), ('cambridge_lower_sec', 'Cambridge Lower Secondary (Grade 6 - 8)'), ('cambridge_igcse', 'Cambridge Upper Secondary / IGCSE (Grade 9 - 10)'), ('gce_alevel', 'Cambridge Advanced / A-Level (Grade 11 - 12)'), ('general', 'General Curriculum & Assessment Overview')], default='cambridge_primary', max_length=50),
        ),
        migrations.AlterField(
            model_name='syllabusitem',
            name='grade',
            field=models.CharField(help_text='e.g. Grade 1, Grade 9 (IGCSE), Playgroup', max_length=100),
        ),
        migrations.AlterField(
            model_name='syllabusitem',
            name='subject',
            field=models.CharField(blank=True, default='All Subjects', help_text="Optional subject or 'All Subjects'", max_length=150),
        ),
        migrations.AlterField(
            model_name='syllabusitem',
            name='term',
            field=models.CharField(blank=True, default='Full Academic Year', help_text='e.g. Full Academic Year, Term 1 & 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='syllabusitem',
            name='title',
            field=models.CharField(help_text='e.g. Grade 1 Annual Academic Syllabus & Curriculum Booklet', max_length=255),
        ),
    ]
