# Generated by Django 6.1.1 on 2026-10-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_seed_news_and_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. The Josephite Chronicle - Annual School Magazine', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('publication_type', models.CharField(choices=[('magazine', 'Annual School Magazine'), ('yearbook', 'Annual Yearbook & Milestones'), ('newsletter', 'Term Newsletter & Gazette'), ('prospectus', 'Academic Prospectus'), ('handbook', 'Student & Parent Handbook')], default='magazine', max_length=50)),
                ('edition', models.CharField(default='Annual Edition 2025-2026', help_text='e.g. Volume XIV, Issue 1', max_length=100)),
                ('academic_year', models.CharField(default='2025-2026', max_length=50)),
                ('cover_image_url', models.TextField(blank=True, default='', help_text='Cover photo preview URL')),
                ('pdf_url', models.TextField(help_text='PDF file URL for the flipbook')),
                ('file_size', models.CharField(blank=True, default='PDF Document', max_length=50)),
                ('pages_count', models.PositiveIntegerField(default=0, help_text='Total number of pages')),
                ('description', models.TextField(blank=True, default='', help_text='Foreword, editorial message, or description')),
                ('editor_name', models.CharField(blank=True, default='SJIS Editorial Board', max_length=150)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Publication',
                'verbose_name_plural': 'School Publications',
                'ordering': ['order', '-publish_date', '-created_at'],
            },
        ),
    ]
