# Generated by Django 6.1.1 on 2026-10-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_seed_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_bg_url',
            field=models.TextField(blank=True, default='', help_text='Custom parallax background image URL or uploaded data URL for the website footer. Recommended: 1920x1080px (16:9) landscape.'),
        ),
    ]
